### ISSUE TITLE
Loose Mesh - Edit Mode

### ISSUE THREAD

**Issue by plumbjet** [Weisl/Collider-Tools#484] opened 2024-05-22 08:39 UTC
Get this crash when i try to add Cylinder collision to grouped objects and place collision based on selection 

![Screenshot 2024-05-22 093513](https://github.com/Weisl/Collider-Tools/assets/7268776/c75f26ec-ea6a-4708-ba18-8758e6e81c7b)

**Comment by Weisl** [comment] 2024-05-23 06:59
I can confirm this bug. 
This happens because Loose Mesh is currently not supported for Edit mode. I made it so that you can't select use mesh in the modal operation but the check does not apply when you set Loose Mesh in the Tool Defaults. I need to add an additional safety check there! 
Thanks for reporting!

**Comment by plumbjet** [comment] 2024-05-23 15:36
Do you think this could be supported in edit mode , Would be a great feature.

**Comment by Weisl** [comment] 2024-07-14 09:59
I split loose mesh from the generation mode. I still need to fix the edit mode issue

**Comment by Weisl** [comment] 2024-07-14 12:53
Fixed for version 1.6. I only need to add the tmp meshes to the tmp_mesh collection and delete them after creation

**Comment by Weisl** [comment] 2024-07-14 19:14
- [ ] Box
- [ ] Sphere
- [ ] Convex
- [ ] Cylinder
- [ ] Mesh
- [ ] OABBOX
- [ ] Auto Convex

**Comment by Weisl** [comment] 2024-08-04 12:11
Should be fixed

**Closed by Weisl** 2024-08-04 12:11 UTC
Labels: bug
